[W 2024-01-19 13:32:43.956 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[W 2024-01-19 13:32:44.049 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-01-19 13:32:44.050 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-01-19 13:32:44.054 ServerApp] jupyter_server_mathjax | extension was successfully linked.
[I 2024-01-19 13:32:44.058 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-01-19 13:32:44.064 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-01-19 13:32:44.064 ServerApp] jupyterlab_git | extension was successfully linked.
[I 2024-01-19 13:32:44.064 ServerApp] nbdime | extension was successfully linked.
[I 2024-01-19 13:32:44.516 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-01-19 13:32:44.563 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-01-19 13:32:44.566 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-01-19 13:32:44.567 ServerApp] jupyter_server_mathjax | extension was successfully loaded.
[I 2024-01-19 13:32:44.568 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-01-19 13:32:44.575 LabApp] JupyterLab extension loaded from /Users/liuhuang/Library/Python/3.8/lib/python/site-packages/jupyterlab
[I 2024-01-19 13:32:44.575 LabApp] JupyterLab application directory is /Users/liuhuang/Library/Python/3.8/share/jupyter/lab
[I 2024-01-19 13:32:44.576 LabApp] Extension Manager is 'pypi'.
[I 2024-01-19 13:32:44.579 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-01-19 13:32:44.585 ServerApp] jupyterlab_git | extension was successfully loaded.
[I 2024-01-19 13:32:44.727 ServerApp] nbdime | extension was successfully loaded.
[I 2024-01-19 13:32:44.729 ServerApp] Serving notebooks from local directory: /Users/liuhuang/learn/code/codelearn
[I 2024-01-19 13:32:44.729 ServerApp] Jupyter Server 2.12.4 is running at:
[I 2024-01-19 13:32:44.729 ServerApp] http://localhost:8888/lab?token=be56aa751a7bb36a4db7037d52057bc6d1bc906515954527
[I 2024-01-19 13:32:44.729 ServerApp]     http://127.0.0.1:8888/lab?token=be56aa751a7bb36a4db7037d52057bc6d1bc906515954527
[I 2024-01-19 13:32:44.729 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-01-19 13:32:44.738 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///Users/liuhuang/Library/Jupyter/runtime/jpserver-60015-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=be56aa751a7bb36a4db7037d52057bc6d1bc906515954527
        http://127.0.0.1:8888/lab?token=be56aa751a7bb36a4db7037d52057bc6d1bc906515954527
[I 2024-01-19 13:32:45.509 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2024-01-19 13:32:46.051 ServerApp] 404 GET /api/kernels/75548dd4-6c88-49e8-bbb2-c1b34f34ed0d?1705642366045 (::1): Kernel does not exist: 75548dd4-6c88-49e8-bbb2-c1b34f34ed0d
[W 2024-01-19 13:32:46.051 ServerApp] wrote error: 'Kernel does not exist: 75548dd4-6c88-49e8-bbb2-c1b34f34ed0d'
    Traceback (most recent call last):
      File "/Users/liuhuang/Library/Python/3.8/lib/python/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
      File "/Users/liuhuang/Library/Python/3.8/lib/python/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
      File "/Users/liuhuang/Library/Python/3.8/lib/python/site-packages/jupyter_server/services/kernels/handlers.py", line 74, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/Users/liuhuang/Library/Python/3.8/lib/python/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/Users/liuhuang/Library/Python/3.8/lib/python/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: 75548dd4-6c88-49e8-bbb2-c1b34f34ed0d)
[W 2024-01-19 13:32:46.069 ServerApp] 404 GET /api/kernels/75548dd4-6c88-49e8-bbb2-c1b34f34ed0d?1705642366045 (3f291f1d92b64b2da22ebd0886746acf@::1) 19.57ms referer=http://localhost:8888/lab/tree/algo/math/matrix.ipynb
[W 2024-01-19 13:32:46.510 ServerApp] 404 GET /api/kernels/75548dd4-6c88-49e8-bbb2-c1b34f34ed0d/channels?session_id=e1f1b760-c225-4ee9-8184-7eb91b689d72 (::1): Kernel does not exist: 75548dd4-6c88-49e8-bbb2-c1b34f34ed0d
[W 2024-01-19 13:32:46.534 ServerApp] 404 GET /api/kernels/75548dd4-6c88-49e8-bbb2-c1b34f34ed0d/channels?session_id=e1f1b760-c225-4ee9-8184-7eb91b689d72 (3f291f1d92b64b2da22ebd0886746acf@::1) 24.96ms referer=None
[W 2024-01-19 13:32:46.538 ServerApp] 404 GET /api/kernels/75548dd4-6c88-49e8-bbb2-c1b34f34ed0d?1705642366535 (::1): Kernel does not exist: 75548dd4-6c88-49e8-bbb2-c1b34f34ed0d
[W 2024-01-19 13:32:46.538 ServerApp] wrote error: 'Kernel does not exist: 75548dd4-6c88-49e8-bbb2-c1b34f34ed0d'
    Traceback (most recent call last):
      File "/Users/liuhuang/Library/Python/3.8/lib/python/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
      File "/Users/liuhuang/Library/Python/3.8/lib/python/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
      File "/Users/liuhuang/Library/Python/3.8/lib/python/site-packages/jupyter_server/services/kernels/handlers.py", line 74, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/Users/liuhuang/Library/Python/3.8/lib/python/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/Users/liuhuang/Library/Python/3.8/lib/python/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: 75548dd4-6c88-49e8-bbb2-c1b34f34ed0d)
[W 2024-01-19 13:32:46.538 ServerApp] 404 GET /api/kernels/75548dd4-6c88-49e8-bbb2-c1b34f34ed0d?1705642366535 (3f291f1d92b64b2da22ebd0886746acf@::1) 1.26ms referer=http://localhost:8888/lab/tree/algo/math/matrix.ipynb
[W 2024-01-19 13:32:49.184 ServerApp] 404 GET /api/kernels/75548dd4-6c88-49e8-bbb2-c1b34f34ed0d/channels?session_id=e1f1b760-c225-4ee9-8184-7eb91b689d72 (::1): Kernel does not exist: 75548dd4-6c88-49e8-bbb2-c1b34f34ed0d
[W 2024-01-19 13:32:49.184 ServerApp] 404 GET /api/kernels/75548dd4-6c88-49e8-bbb2-c1b34f34ed0d/channels?session_id=e1f1b760-c225-4ee9-8184-7eb91b689d72 (3f291f1d92b64b2da22ebd0886746acf@::1) 4.49ms referer=None
[W 2024-01-19 13:32:49.193 ServerApp] 404 GET /api/kernels/75548dd4-6c88-49e8-bbb2-c1b34f34ed0d?1705642369185 (::1): Kernel does not exist: 75548dd4-6c88-49e8-bbb2-c1b34f34ed0d
[W 2024-01-19 13:32:49.194 ServerApp] wrote error: 'Kernel does not exist: 75548dd4-6c88-49e8-bbb2-c1b34f34ed0d'
    Traceback (most recent call last):
      File "/Users/liuhuang/Library/Python/3.8/lib/python/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
      File "/Users/liuhuang/Library/Python/3.8/lib/python/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
      File "/Users/liuhuang/Library/Python/3.8/lib/python/site-packages/jupyter_server/services/kernels/handlers.py", line 74, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/Users/liuhuang/Library/Python/3.8/lib/python/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/Users/liuhuang/Library/Python/3.8/lib/python/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: 75548dd4-6c88-49e8-bbb2-c1b34f34ed0d)
[W 2024-01-19 13:32:49.194 ServerApp] 404 GET /api/kernels/75548dd4-6c88-49e8-bbb2-c1b34f34ed0d?1705642369185 (3f291f1d92b64b2da22ebd0886746acf@::1) 1.41ms referer=http://localhost:8888/lab/tree/algo/math/matrix.ipynb
[I 2024-01-19 13:32:51.981 LabApp] Build is up to date
[W 2024-01-19 13:32:53.060 ServerApp] 404 GET /api/kernels/c37b0ebb-c6bd-4cd8-8d43-cb1a38bb47d0?1705642373055 (::1): Kernel does not exist: c37b0ebb-c6bd-4cd8-8d43-cb1a38bb47d0
[W 2024-01-19 13:32:53.061 ServerApp] wrote error: 'Kernel does not exist: c37b0ebb-c6bd-4cd8-8d43-cb1a38bb47d0'
    Traceback (most recent call last):
      File "/Users/liuhuang/Library/Python/3.8/lib/python/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
      File "/Users/liuhuang/Library/Python/3.8/lib/python/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
      File "/Users/liuhuang/Library/Python/3.8/lib/python/site-packages/jupyter_server/services/kernels/handlers.py", line 74, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/Users/liuhuang/Library/Python/3.8/lib/python/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/Users/liuhuang/Library/Python/3.8/lib/python/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: c37b0ebb-c6bd-4cd8-8d43-cb1a38bb47d0)
[W 2024-01-19 13:32:53.062 ServerApp] 404 GET /api/kernels/c37b0ebb-c6bd-4cd8-8d43-cb1a38bb47d0?1705642373055 (3f291f1d92b64b2da22ebd0886746acf@::1) 2.03ms referer=http://localhost:8888/lab/tree/algo/math/matrix.ipynb
